name: Convert Meixiu Yu's publications

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script 002
        env: 
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: python mongodb/002-mongodb2md.py

      - name: commit and push
        env:
          PUBLICATIONS_TOKEN: ${{ secrets.PUBLICATIONS_TOKEN }}
        run: |
          cd publication
          git init
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git config user.name $GITHUB_ACTOR
          git add .
          git commit -m "Update Meixiu Yu's publications from Action"
          git push --force https://$GITHUB_ACTOR:$PUBLICATIONS_TOKEN@github.com/$GITHUB_REPOSITORY.git master:publications
          
  update:
    needs: collect
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout parent repo
        uses: actions/checkout@v4
        with: 
          repository: longavailable/longavailable.github.io
          token: ${{ secrets.PUBLICATIONS_TOKEN }}
          submodules: recursive

      - name: Pull & update submodules recursively
        run: | 
          git submodule deinit -f myCollections/_publications
          rm -rf .git/modules/myCollections/_publications
          git rm -r myCollections/_publications
          git submodule add -b publications https://github.com/longavailable/generate-publication-overview.git ./myCollections/_publications
          #git submodule update --recursive --remote
          
      - name: Commit & push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
