name: Collect Meixiu Yu's publications

on:
  push:
    branches:
      - main
  schedule:
    - cron: '8 8 8 */3 *' # runs at 8:08 UTC on 8th day of month in every 3rd month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script 001
        env: 
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: python mongodb/001-googleScholar2mongodb.py

      - name: execute python script 002
        env: 
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: python mongodb/002-mongodb2md.py

      - name: commit and push
        env:
          PUBLICATIONS_TOKEN: ${{ secrets.PUBLICATIONS_TOKEN }}
        run: |
          cd publication
          git init
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git config user.name $GITHUB_ACTOR
          git add .
          git commit -m "Update Meixiu Yu's publications from Action"
          git push --force https://$GITHUB_ACTOR:$PUBLICATIONS_TOKEN@github.com/$GITHUB_REPOSITORY.git master:publications
